### PR TITLE
UnknownFormatConversionException fix

### PR DESCRIPTION
**Pull request by ivanobulo**
Fix for the https://github.com/codeclimate-community/codeclimate-scalastyle/issues/11

This would print an error when running codeclimate locally with CODECLIMATE_DEBUG=1

### CODE REVIEW

**Comment by ivanobulo** [comment]
@filipesperandio 👈poke

**Comment by filipesperandio** [comment]
Sorry mate, lots of things in my plate.
Will pick this up soon.

**Comment by walkafwalka** [comment]
@filipesperandio Really looking forward to this PR if it fixes the scalastyle bug.

**Review by filipesperandio — APPROVED** [review]

**Comment by filipesperandio** [comment]
This will be released as `beta` in a few minutes.

**Comment by walkafwalka** [comment]
> This will be released as `beta` in a few minutes.

```
$ docker run -it --rm -e CODECLIMATE_CODE="$PWD" -v "$PWD":/code -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -e scalastyle:beta
Skipped scalastyle: Channel beta not found for scalastyle, available channels: ["stable"]
```

**Comment by filipesperandio** [comment]
Ah, right. `beta` is not available in the CLI, though, this version is already the latest on dockerhub, meaning the CLI gets it on the default/stable channel.

On codeclimate.com it is going to be in `beta` for while.

**Pull request merged**
